### ISSUE TITLE
Clean away console output from "No encoding supplied: defaulting to UTF-8"

### ISSUE THREAD

**Issue by grayskripko** [Azure/rAzureBatch#26]
https://github.com/Azure/doAzureParallel/issues/101

**Comment by brnleehng** [comment]
Will get this fix while refactoring rAzureBatch SDK

We were running:
`httr::content(response, content)` which causes the guess_encoding and printing this message. 

It should be changed to this:
httr::content(response, content, encoding = "UTF-8")

**Comment by grayskripko** [comment]
Brian, you can find exact locations of ```httr::content``` calls using the attached link

**Comment by brnleehng** [comment]
Here's the location:
https://github.com/Azure/rAzureBatch/blob/master/R/batch_service.R#L95-L100

**Comment by grayskripko** [comment]
not only. Please go to https://github.com/Azure/doAzureParallel/issues/101
