### ISSUE TITLE
downloadBlob fails to write to disk

### ISSUE THREAD

**Issue by dustindall** [Azure/rAzureBatch#27]
I've been using this package for my interaction with Azure Storage. I tried downloading files locally on an Azure VM and nothing downloaded. I noticed the write variable is not passed  into the final httr::response in callStorage.

**Comment by dustindall** [comment]
pull request #28

**Comment by brnleehng** [comment]
Thanks Dustin, 

I'm actually doing a major refactor of this package.. The PR should be coming out in a couple of days. If you are curious on the changes, the branch name is fix/abstract-azure-functions

This also includes a similar change in your PR :)
