### ISSUE TITLE
uploadBlob NULL returned

### ISSUE THREAD

**Issue by dustindall** [Azure/rAzureBatch#30]
When I use uploadBlob without a sasToken the blob is uploaded and NULL is returned to the console. Null is not returned when I pass in a sasToken. See below.

![image](https://user-images.githubusercontent.com/8218382/29945936-0f3c23bc-8e58-11e7-800e-d706d051bc8b.png)

Both work, however, i don't think NULL should be returned.

**Comment by brnleehng** [comment]
Will get this fix.

Thanks!
Brian
