### ISSUE TITLE
Error: 'getPool' is not an exported object from 'namespace:rAzureBatch'

### ISSUE THREAD

**Issue by sazari** [Azure/rAzureBatch#56]
I am trying to run caret your example and get this error while trying to execute the train command after pool successfully started.

I am able to run Monte Carlo tutorial.

**Comment by brnleehng** [comment]
@sazari,

Sorry for the late response,

We've updated the doAzureParallel package to have the exported object. 

Thanks,
Brian

**Comment by sazari** [comment]
Pulled updated code, working. Thank you very much!
